services:
  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks: 
      - inception
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes: 
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/oboucher/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/oboucher/data/mariadb'

networks:
  inception:
    driver: bridge