FROM debian:buster


#--- variable ---#
ARG PHP_VERSION=7.3


RUN apt-get update && apt-get upgrade -y && \
	#--- dependencies ---#
	apt-get install -y php${PHP_VERSION}-fpm wget php${PHP_VERSION}-mysql mariadb-client && \
	#--- cleaning cache ---#
	apt-get clean && rm -rf /var/lib/apt/lists/* 

#--- config ---#
COPY conf/www.conf /etc/php/${PHP_VERSION}/fpm/pool.d/


#--- WP-CLI ---#
RUN wget -O wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && \
	mv wp-cli.phar /usr/local/bin/wp


#--- tool ---#
COPY tools/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh


#--- ports ---#
EXPOSE 9000


#--- working directory ---#
WORKDIR /var/www/html


#--- execution ---#
ENTRYPOINT ["/entrypoint.sh"]