FROM debian:buster

#--- Update verification ---#
RUN apt-get update && apt-get upgrade -y

#--- dependencies ---#
RUN apt-get install -y nginx openssl

#--- certificat ---#
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout nginx-selfsigned.key -out nginx-selfsigned.crt

COPY conf/nginx.conf /etc/nginx/nginx.conf

EXPOSE 443

CMD [ "nginx", "-g", "daemon off;" ]